<h1><?php echo $this->escapeHtml($vehicle->getTitle()); ?></h1>
<p class="description">
    <?php echo $this->escapeHtml($vehicle->getDescription()); ?>
</p>

<p class="price">
    <?php echo number_format($vehicle->getConsumerPrice(), 2, ',', '.'); ?>
    <?php echo $vehicle->getCurrency(); ?>
</p>

<?php foreach ($vehicle->getImageCollection() as $img) : ?>
    <img src="<?php echo $img; ?>" alt="" style="float: left; margin: 1em;" />
<?php endforeach; ?>